name: Run

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '*/40 * * * *'


jobs:
  deployment:

    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v2
    - name: Set env file
        run: |
          touch .env
          echo "TWITTER_CONSUMER_KEY ${{ secrets.TWITTER_CONSUMER_KEY }}" > .env
          echo "TWITTER_CONSUMER_SECRET ${{ secrets.TWITTER_CONSUMER_SECRET }}" > .env
          echo "TWITTER_ACCESS_TOKEN_KEY ${{ secrets.TWITTER_ACCESS_TOKEN_KEY }}" > .env
          echo "TWITTER_ACCESS_TOKEN_SECRET ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}" > .env
        
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm install -g ts-node
    - run: npm run dev
          # TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
          # TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          # TWITTER_ACCESS_TOKEN_KEY: ${{ secrets.TWITTER_ACCESS_TOKEN_KEY }}
          # TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
    # - name: Use Node.js ${{ matrix.node-version }}
    #   uses: actions/setup-node@v2
    # - name: Install Dependencies
    #   run: npm install
    # - name: Install ts-node
    #   run: npm install -g ts-node
    # - name: Run dev
    #   run: npm run dev
    #     env:
    #       TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
    #       TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
    #       TWITTER_ACCESS_TOKEN_KEY: ${{ secrets.TWITTER_ACCESS_TOKEN_KEY }}
    #       TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}